### ISSUE TITLE
NPE if rule is defined in profile

### ISSUE THREAD

**Issue by masooh** [1and1/ono-extra-enforcer-rules#10]
```xml
<profile>
    <id>ono-extra-enforcer-rules</id>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-enforcer-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>net.oneandone.maven</groupId>
                        <artifactId>ono-extra-enforcer-rules</artifactId>
                        <version>0.2</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <rules>
                        <ForbidOverridingManagedDependenciesRule />
                        <ForbidOverridingManagedPluginsRule />
                        <ForbidDependencyManagementInSubModulesRule />
                        <ManageAllModulesRule />
                    </rules>
                </configuration>
            </plugin>
        </plugins>
    </build>
</profile>
```

```
Caused by: java.lang.NullPointerException
	at  net.oneandone.maven.rules.common.AbstractRule.ruleDefinedInProject(AbstractRule.java:83)
	at net.oneandone.maven.rules.common.AbstractRule.ruleIsDefinedInProjectOrNotModuleParent(AbstractRule.java:70)
	at net.oneandone.maven.rules.ForbidDependencyManagementInSubModulesRule.checkForSubmoduleDependencyManagement(ForbidDependencyManagementInSubModulesRule.java:48)
	at net.oneandone.maven.rules.ForbidDependencyManagementInSubModulesRule.execute(ForbidDependencyManagementInSubModulesRule.java:37)
	at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:193)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
```

**Comment by masooh** [comment]
solved with 0.2.1
